apiVersion: apps/v1
kind: Deployment
metadata:
  name: vercel-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vercel
  template:
    metadata:
      labels:
        app: vercel
    spec:
      containers:
        - name: vercel-redis
          image: redis:latest
          ports:
            - containerPort: 6379
        - name: vercel-content-resolver
          image: vercel-content-resolver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
          - name: PORT
            value: "9000"
        - name: vercel-api
          image: vercel-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          envFrom:
          - configMapRef:
              name: vercel-api-env
---
apiVersion: v1
kind: Service
metadata:
  name: vercel-service
spec:
  type: LoadBalancer
  selector:
    app: vercel
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: api
      port: 8000
      targetPort: 8000
    - name: content-resolver
      port: 9000
      targetPort: 9000