version: '3'

services:
  api:
    build:
      context: ./apps/api
    image: vercel-api:latest

  content-resolver:
    build:
      context: ./apps/content-resolver
    image: vercel-content-resolver:latest
  
  repo-builder:
    build:
      context: ./apps/repo-builder
    image: git-repo-builder:latest
